import LoginComponent from '@/components/Login';
import Head from 'next/head'
import { AuthContext } from '@/context/AuthContext';
import { useState } from 'react';

export default function Home() {


  const [auth, setAuth] = useState()


  const userAuth = (userAuthData: any) => {
    setAuth(userAuthData)
  }
  console.log(auth);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthContext.Provider value={{ auth, userAuth }}>

        <LoginComponent />
        {/* <Layout>
        <HomePage />
      </Layout> */}

        {/* Дали е логнат потребителят*/}
      </AuthContext.Provider>
    </>
  )
}
