import LoginComponent from '@/components/Login';
import Layout from '@/components/layout/MainLayout';
import HomePage from '@/components/pages/HomePage';
import Head from 'next/head'

export default function Home() {
  let stan: number;


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginComponent />
      {/* <Layout>
        <HomePage />
      </Layout> */}

      {/* Дали е логнат потребителят*/}
    </>
  )
}
